# -*- coding: utf-8 -*-
"""Madayag_2ndLabExam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GQU_ryNiACal5SvqLctE4EZuYkXMlDz4
"""

# !pip install apyori
# Requirement already satisfied: apyori in /usr/local/lib/python3.12/dist-packages (1.1.2)

# import necessary libraries
import pandas as pd
import numpy as np
from apyori import apriori

# import dataframe
df = pd.read_csv('symptoms.csv', header = None)
print(df)

transactions = []

for i in range (0, 99):
  transactions.append([str(df.values[0,9] for j in range(0,3))])

print(transactions)

rules = apriori(transactions = transactions,
                min_support = 0.2,
                min_confidence = 0.5,
                min_lift = 1,
                min_length = 2,
                max_length = 2)

# print(rules)

results = list(rules)
print(rules)

# def inspect(results):
#   lhs = [tuple(results[2][0])[2] for result in results]
#   rhs = [tuple(results[2][0])[2] for result in results]
#   support = [results[1] for result in results]
#   confidence = [results[2][0][2] for result in results]
#   lift = [results[2][0][3] for result in results]
#   return zip(list(lhs, rhs, support, confidence, lift))

# data = inspect(results)

# resultsinDataFrame = pd.DataFrame(data,
# columns = ['Left Hand Side',
#                 'Right Hand Side',
#                 'Support',
#                 'Confidence',
#                 'Lift'])

# data = inspect(results)
# resultsinDataFrame = pd.DataFrame(data,
#                                   columns = [
#                                       'Left Hand Side',
#                                       'Right Hand Side',
#                                       'Support',
#                                       'Confidence',
#                                       'Lift'])

# # resultsinDataFrame = np.column_stack(n_stack = 1, lift = 10)
# print(resultsinDataFrame)

def inspect(results):
  #lhs
    lhs = []
    rhs = []
    support = []
    confidence = []
    lift = []

    # for in range (0,99):
    # for results in resul:
    for result in results:
        for statistic in result.ordered_statistics:
            lhs.append(tuple(statistic.items_base))
            rhs.append(tuple(statistic.items_add))
            support.append(result.support)
            confidence.append(statistic.confidence)
            lift.append(statistic.lift)

    return list(zip(lhs, rhs, support, confidence, lift))

data = inspect(results)
resultsinDataFrame = pd.DataFrame(data, columns = [
                'Left Hand Side',
                'Right Hand Side',
                'Support',
                'Confidence',
                'Lift'])

# data = inspect(results);
# resultsinDataFrame = pd.DataFrame(inspect(results), columns = [
#                 'Left Hand Side',
#                 'Right Hand Side',
#                 'Support',
#                 'Confidence',
#                 'Lift']);

# resultsinDataFrame = (n.stack = 1, lift = 10)

print(resultsinDataFrame)

"""Explanation:

The dataset has a support of 1.0. It indicates that the itemset is not frequent enough to be considered significant.

The dataset has a confidence of 1.0. It indicates that the estimated value is very close to the true population parameter.

The dataset has a lift of 1.0. In other words, the rule is independent. The rule is not useful for predicting any occurence.

"""