# -*- coding: utf-8 -*-
"""Madayag_LabExam1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X3UdILr-mgmBG26iut1nHrARwYWDx0Yq
"""

# Step 1: Import necessary libraries
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from sklearn.impute import SimpleImputer

from sklearn.cluster import KMeans

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# Step 2: Import the dataset
file_path ='anime_rating.csv'
df = pd.read_csv(file_path, encoding='latin1')
print(df)

# iloc
X = df.iloc[:,:].values

# check for missing values
print("Check if there is a missing value in the whole dataset:")
print(df.isnull().sum().sum()) # 1 missing value

# fill for missing values
imputer = SimpleImputer(missing_values=np.nan, strategy='median')
X[:,[4]] = imputer.fit_transform(X[:,[4]])

# encoding
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1,2,3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

print(X)

# Step 3: Elbow Method
wcss = []

#import sklearn.sparse
import scipy.sparse
if isinstance(X, np.ndarray) and X.dtype == object and X.ndim == 0 and isinstance(X.item(), scipy.sparse.spmatrix):
# if isinstances(X, np.ndarray) and X.dtype == object and y.ndim and X.ndim == 0 and isinstance(X.item(), scipy.sparse.spmatrix):
    X_processed = X.item()
    # X = wcss
    #wcss
else:
    X_processed = X

for i in range(1,11):
  kmeans = KMeans(n_clusters=i, init='k-means++', random_state=42)
  kmeans.fit(X_processed)
  wcss.append(kmeans.inertia_)

plt.title("Elbow Method")
plt.plot(range(1,11), wcss, marker='o')
plt.xlabel("No. of clusters")
plt.ylabel("Y")
plt.show()

kmeans = KMeans(n_clusters=3, init='k-means++', random_state=42)
X_processed = kmeans.fit_predict(X_processed)

plt.scatter(X_processed[kmeans==0,0], X_processed[kmeans==0,1], s=100, c='red', label='Cluster 1')
plt.scatter(X_processed[kmeans==1,0], X_processed[kmeans==1,1], s=100, c='green', label='Cluster 2')
plt.scatter(X_processed[kmeans==2,0], X_processed[kmeans==2,1], s=100, c='blue', label='Cluster 3')

plt.scatter(kmeans.cluster_centers_[0,4], kmeans.cluster_centers_[0,9], s=200, c='yellow', label='Centroids')

plt.title("Clusters")
plt.legend()
plt.xlabel("No. of clusters")
plt.ylabel("y")
plt.show()

"""The data doesnt have clusters"""